# Generated by Django 3.2.5 on 2021-08-03 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210803_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agents',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='is agent?', verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
