# Generated by Django 3.2.5 on 2021-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210803_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_info',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.URLField(null=True),
        ),
    ]
