# Generated by Django 3.2.5 on 2021-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210803_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_info',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='agent_info',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
