# Generated by Django 3.2.5 on 2023-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='region',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
