# Generated by Django 3.2.5 on 2021-08-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_agents_agent'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactwithagent',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authusers.agents'),
            preserve_default=False,
        ),
    ]
