# Generated by Django 3.2.5 on 2023-05-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactwithagent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact With Agent', 'verbose_name_plural': 'Contacts With Agent'},
        ),
    ]
