# Generated by Django 3.2.5 on 2021-08-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210803_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districts',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AddField(
            model_name='posts',
            name='muljal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
