# Generated by Django 3.2.5 on 2021-08-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210803_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='muljal',
            new_name='adress',
        ),
    ]
