# Generated by Django 3.2.5 on 2021-08-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210805_0010'),
        ('main', '0004_rename_muljal_posts_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='diller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agents'),
        ),
    ]
