# Generated by Django 3.2.5 on 2021-08-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subscribeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
