# Generated by Django 3.2.5 on 2021-08-11 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_posts_is_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AddField(
            model_name='posts',
            name='year_build',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
