# Generated by Django 3.2.5 on 2021-08-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='authusers.customuser'),
            preserve_default=False,
        ),
    ]
