# Generated by Django 3.2.5 on 2021-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='agents/profile/img'),
        ),
    ]
